// Auto-generated by scripts/prepare-reel.mjs - DO NOT EDIT MANUALLY
export interface VideoClipInfo {
  id: string;
  file: string;
  originalName: string;
  durationInSeconds: number;
  durationInFrames: number;
}

export interface ManifestData {
  audioFileName: string;
  originalAudioName: string;
  audioDuration: number;
  fps: number;
  durationInFrames: number;
  videos: VideoClipInfo[];
  outputFileName: string;
}

export const MANIFEST: ManifestData = {
  "audioFileName": "historia_del_wifi.mp3",
  "originalAudioName": "Historia del WiFi.mp3",
  "audioDuration": 5.042,
  "fps": 24,
  "durationInFrames": 121,
  "videos": [
    {
      "id": "clip_01",
      "file": "clip_01.mp4",
      "originalName": "1_video.mp4",
      "durationInSeconds": 1,
      "durationInFrames": 24
    },
    {
      "id": "clip_02",
      "file": "clip_02.mp4",
      "originalName": "2_ok.mp4",
      "durationInSeconds": 1,
      "durationInFrames": 24
    },
    {
      "id": "clip_03",
      "file": "clip_03.mp4",
      "originalName": "03_1.mp4",
      "durationInSeconds": 1,
      "durationInFrames": 24
    },
    {
      "id": "clip_04",
      "file": "clip_04.mp4",
      "originalName": "3_2_ok.mp4",
      "durationInSeconds": 1,
      "durationInFrames": 24
    },
    {
      "id": "clip_05",
      "file": "clip_05.mp4",
      "originalName": "08_final.mp4",
      "durationInSeconds": 1.042,
      "durationInFrames": 25
    }
  ],
  "outputFileName": "Historia-del-WiFi-Reel.mp4"
};

export default MANIFEST;
